### ISSUE TITLE
Use with Sprockets

### ISSUE THREAD

**Issue by rbmntjs** [thejameskyle/jekyll-babel#5]
Hey,

I’m relatively new to the React side of things, but I would love to set up a clean pipeline for my code. I’m currently using the latest `jekyll-assets` gem, and now I’m stuck. Is it just me, or is it perhaps non-trivial to use `jekyll-babel` inside of the Sprockets workflow?

I have both gems hooked up properly, but `{% asset_path cart.jsx %}` points to a plain React/JSX file. `{% javascript cart %}` serves `cart.js`, with the YAML front matter hack still intact. So, how do I ‘activate’ `jekyll-babel`?

Thanks from this eager-to-learn hopeful.

**Comment by jamiebuilds** [comment]
I'm honestly not sure, I mostly copied this jekyll plugin from the jekyll-coffee plugin. It should behave the same as that one, but I don't know enough about sprockets to say.

**Comment by rbmntjs** [comment]
So! I found [this explanation](https://biesnecker.com/2014/10/13/integrating-react-into-jekyll/) of what my setup kinda looks like, but it’s not helping one-to-one. I load the required Gems, but the `ext.rb` changes I leave out, as they can’t seem to work. Then, it works as advertised: an asset pipeline that converts `.jsx` files ready for production. Just don’t quote me on this – I’d better ask around to see why this works. Until then, be warned :)
